import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes"; // ✅ IMPORTANTE

const geistSans = Geist({
 variable: "--font-geist-sans",
 subsets: ["latin"],
});

const geistMono = Geist_Mono({
 variable: "--font-geist-mono",
 subsets: ["latin"],
});

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (

  <html lang="pt-BR">
   <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    <ThemeProvider
     attribute="class"
     defaultTheme="theme-2"
     themes={[
      'theme-0',
      'theme-1',
      'theme-2',
      'theme-3',
      'theme-4',
      'theme-5',
      'theme-6',
      'theme-7',
     ]}
     storageKey="theme"
    >
     {children}
    </ThemeProvider>
   </body>
  </html >
 );
}
